spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hanhuoer/spring-cloud-sample-config
          search-paths: repo
          username:
          password:
      label: master
    bus:
      enabled: true
      trace:
        enabled: true
server:
  port: 20040
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/